### ISSUE TITLE
Tech Issue

### ISSUE THREAD

**Issue by xjiang1** [Jlangway1/WebTech-Project#1]
1. Great footer design, but the sitemap page has no navigation bar like other pages. Maybe consider adding the same navigation bar to the Sitemap page.
2. Courses and About Us page have a horizontal line above the footer, but other pages don't have this horizontal line. Maybe consider remove the line from these two pages or add one line on all pages to make it consistent.
3. Navigation bar has many vertical lines to divide the different buttons. That's a good design! But the first vertical line on the left is longer than all other vertical lines, maybe make it shorter to match with other vertical lines.

**Comment by Jlangway1** [comment]
1. I added the navigation bar onto the sitemap page to keep consistent with the overall webpage
2. I removed the vertical lines from the two pages you listed - good call!
3. I will attempt to fix the navigation bar as it is something I noticed too

Thanks for the input!
