### ISSUE TITLE
Project Peer Review

### ISSUE THREAD

**Issue by ywzheng2** [Jlangway1/WebTech-Project#3]
**Two technical issues/bugs/suggestions:**

- Your logo and the navigation bar texts do not align. On your ljmga.css file, you can consider change the "margin-top: 1px;" under img to a negative value (e.g. "margin-top:-8px;") to move the logo upward. 
- You can add a navigation bar to the Sitemap page to make your pages consistent. 

 
**Two suggestions on content:**

- For the "Founders" and "Courses" pages, you can consider adding a short bio for each founder and including a description of each course's unique features. 
- Since your target audience includes people who have never played golf, you can consider including a short section explaining the golf score on the "Past Results" page. Also, you might want to consider including better pictures of the scorecard or cropping the images.

**Comment by Jlangway1** [comment]
In terms of the technical issues:
1. I used your advice by adding margin-top: -8px and that was great advice!
2. I added the navigation bar to the sitemap page to keep the overall website standard.

In terms of the content suggestions:
1. I added bios to the founders as suggested.
2. I cleaned up the past results page.

Thanks for the input!
